language: go

os:
  - linux

go:
  - 1.x
  - 1.7.x
  - master

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - go build
  - go test -v -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

notifications:
  slack:
    secure: J3mdASS21ly9TLJL0NL48k56chy3i5SNq0k5ApL394NimsZoG8cRpp4pz+J1BQdgqP5unL421thhY4q7A6lebcs/ezHhsv5oFAwMCdvL3nqgMHDlBiFhUSMS1ttbrdb2f7PH760oEn/0kMFXsV3iamTP/r1yRw1tdl5g+R5WFLa52r70PkOlfbcnucr9R3oWflrjaxVUYxeB3I7X0opn8CQIFaq3jxCKeq0PS2LIC9SBH+rl/wuYj3KvG34pL9pf7w6IRP30CJJBhHzUW6Y+FKTAGpeVTNGKZDk/ZBaijF3i6FFmmqDtZWHIXoLz6eNls2E183La8S84y0TAHyHDp8VvQ6G/6zJiuboF3t01aCAFAgHmmbik8Chyt2ZX3/2AQ7f6CfuAzX/gOIb+nsVa6J84L35q6goMT/PdTuutvirKse0oRQTv7LlmU+K1rosQruOHXqTP4dDWwPo2pJRN02aNZzoj7lacN0deAYAice/SI4OKUbtQHDgJh03OMRYe+/RuJ9LtaS7X2RwCz2bAxG2l+hmNIsEGICoYflQEcvmxRDurJaQgPvDUG0f1fIU7d65XxMGnNelzRvX6aKYqCO6qg5ALsU92RLW3O5EpND0/zc5II/hJgShOX3tC3mgguvAGnimNs3oX41Gt4JExB/N2SDFTGVglBMqiuIrsUVQ=
